# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dotter}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Piotr Sarnacki"]
  s.date = %q{2009-10-16}
  s.description = %q{Simple lib drawing dots on transparent image}
  s.email = %q{drogus@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "dotter.gemspec",
     "init.rb",
     "lib/dotter.rb",
     "lib/dotter/dot.rb",
     "lib/dotter/gmap.rb",
     "lib/dotter/lat_lng.rb",
     "lib/dotter/point.rb",
     "lib/dotter/tile.rb",
     "spec/dotter/dot_spec.rb",
     "spec/dotter/gmap_spec.rb",
     "spec/dotter/lat_lng_spec.rb",
     "spec/dotter/point_spec.rb",
     "spec/dotter/tile_spec.rb",
     "spec/dotter_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/drogus/dotter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple lib drawing dots on transparent image}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/dotter/gmap_spec.rb",
     "spec/dotter/point_spec.rb",
     "spec/dotter/tile_spec.rb",
     "spec/dotter/dot_spec.rb",
     "spec/dotter/lat_lng_spec.rb",
     "spec/dotter_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
